server:
  port: 8989

# 数据源
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: password

# MyBatis
mybatis:
  # 搜索指定包别名 默认不支持通配符 此处优化自定义MyBatisConfig配置
  typeAliasesPackage: com.fadedos.*.entity
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath*:mapper/**/*Mapper.xml
  # 加载全局的配置文件 :骆驼命名/自动返回主键/log/cache等设置 MyBatisConfig中提取
  configLocation: classpath:mybatis/mybatis-config.xml

# 日志
logging:
  level:
    com.fadedos: debug
    org.springframework: warn